### PR TITLE
Refactor function names in R/CHANGED-pre-msa-tree.R

### PR DESCRIPTION
**Pull request by teddyCodex**
# Description

Refactored functions in R/CHANGED-pre-msa-tree.R based on #7 

| Original | Modified | User Facing |
| :---         |     :---    |          :--- |
| convert_aln2fa   | convertAlignment2FA     | ✅    |
| to_titlecase     | convert2TitleCase    |    ✅  |
| add_leaves    | addLeaves2Alignment       | ✅    |
| generate_all_aln2fa     | generateAllAlignments2FA       | ✅     |
| convert_aln2tsv     | convertAlignment2TSV       |      ✅ |
| convert_accnum2fa     | convertAccNum2FA       |   ✅    |
| add_name     | addName       |      ✅ |
| map_acc2name     | mapAcc2Name       |     ✅ |
| rename_fasta     | renameFA       |     ✅ |
| acc2fa     | acc2FA       |    ✅  |

Fixes issue #37 

## What kind of change(s) are included?

- [ ] Feature (adds or updates new capabilities)
- [x] Bug fix (fixes an issue).
- [ ] Enhancement (adds functionality).
- [ ] Breaking change (these changes would cause existing functionality to not work as expected).

# Checklist

Please ensure that all boxes are checked before indicating that this pull request is ready for review.

- [x] I have read and followed the [CONTRIBUTING.md](CONTRIBUTING.md) guidelines.
- [x] I have searched for existing content to ensure this is not a duplicate.
- [x] I have performed a self-review of these additions (including spelling, grammar, and related).
- [x] I have added comments to my code to help provide understanding.
- [x] I have added a test which covers the code changes found within this PR.
- [x] I have deleted all non-relevant text in this pull request template.
- [x] **Reviewer assignment**: Tag a relevant team member to review and approve the changes.

### CODE REVIEW

**Comment by teddyCodex** [comment]
@jananiravi @Seyi007 @the-mayer 
File containing other occurrences of the functions. Please let me know if I should commit this file as well.

[function_occurrences.txt](https://github.com/user-attachments/files/17270185/function_occurrences.txt)

**Comment by jananiravi** [comment]
convertAccNumber2FA --> convertAccNum2FA
mapAccession2Name --> mapAcc2Name

changes made in original issue #7 + this specific issue. could you double-check, @teddyCodex?

**Comment by teddyCodex** [comment]
@jananiravi changes for this file effected.

**Review by the-mayer — APPROVED** [review]
Thanks for your contributions, merging!

**Pull request merged**
