### PR TITLE
InlP figures implementation

### LINKED ISSUE #88: [FEAT] Fix, Implement InlP Figure
We need to add figures 2 and 3 from the InlP paper, https://www.microbiologyresearch.org/docserver/fulltext/mgen/8/7/mgen000828.pdf. We have some code, written when the paper was published, that was used to generate those figures, but it's likely out of date and wasn't written to use MolEvolvR's job outputs. The figure will need to be integrated into the MolEvolvR web app, both for displaying on the site and including in the downloadable report.

Any progress on the following tasks would be appreciated:
- getting the figure to render with its original inputs
- adapting the code to use MolEvolvR's job output

I've included a sample MolEvolvR job output, `5uNQ9l`, to demonstrate what files are typically included in a MolEvolvR job.

[5uNQ9l_full.tar.gz](https://github.com/user-attachments/files/17310980/5uNQ9l_full.tar.gz)

See PR #91 for the current code. If you self-assign this issue also assign yourself to that PR. Once your PR is ready, you can convert it from a draft to a regular PR and request review. If you prefer to not use that PR as a starting point, you're also free to create your own.

### PR DESCRIPTION
**Pull request by falquaddoomi**
# Description

This PR contains a very work-in-progress implementation of figures 2 and 3 from the InlP paper, https://www.microbiologyresearch.org/docserver/fulltext/mgen/8/7/mgen000828.pdf. The PR
is intended as a starting point, so you don't have to go and find the original code from the papers, but it definitely needs a lot of work! See issue #88 for more details.

Closes #88.

## What kind of change(s) are included?

- [x] Feature (adds or updates new capabilities)
- [ ] Bug fix (fixes an issue).
- [ ] Enhancement (adds functionality).
- [ ] Breaking change (these changes would cause existing functionality to not work as expected).

# Checklist

Please ensure that all boxes are checked before indicating that this pull request is ready for review.

- [x] I have read and followed the [CONTRIBUTING.md](CONTRIBUTING.md) guidelines.
- [x] I have searched for existing content to ensure this is not a duplicate.
- [ ] I have performed a self-review of these additions (including spelling, grammar, and related).
- [ ] I have added comments to my code to help provide understanding.
- [ ] I have added a test which covers the code changes found within this PR.
- [x] I have deleted all non-relevant text in this pull request template.
- [ ] **Reviewer assignment**: Tag a relevant team member to review and approve the changes.

### CODE REVIEW

**Comment by valentina-buoro** [comment]
Hi @epbrenner @jananiravi .

I tried running some files in the job results folder with the figure-generating code, and I'm getting an error `Error in plan(strategy = plan, .skip = T) :  could not find function "plan"` . Searching the code for the `plan` function gave no results. Pls could you give me a pointer to what may be going on.
The function I ran was `inlp_fig2` .

**Comment by jananiravi** [comment]
@falquaddoomi @epbrenner could you look into this?

**Comment by falquaddoomi** [comment]
So, I'm not an R developer, so take this all with a grain of salt. Anyway...

@valentina-buoro, [plan](https://www.rdocumentation.org/packages/future/versions/1.32.0/topics/plan) is from the `future` library; it basically tells R how to resolve "futures", functions that should be executed asynchronously (i.e., not in the main thread). Since it's in the `future` library, adding `library(future)` somewhere near the top of the file should resolve it.

I'm not sure why you're getting that message, though. The `plan()` invocation is almost certainly coming from another library, which is why you're not seeing it in the code, but I don't know enough about R to say whether the author of that library is correctly loading `future` or if that's the user's responsibility.

**Comment by jananiravi** [comment]
If we know for sure that we're invoking `future::plan()` best to call it explicitly to avoid any confusion. @the-mayer are we using future enough to warrant adding it as a dependency (to function imports)? Then even the library call upfront in this script might not be needed. 

Thanks for addressing this, @falquaddoomi

**Comment by the-mayer** [comment]
Another way to make sure all dependencies are loaded when working on a package is to run `devtools::load_all()`. This will attempt to load all MolEvolvR exported functions, as well as any declared imports. `future::plan()` is declared in the package NAMESPACE and thus would be loaded by a call to `devtools::load_all()`

**Comment by valentina-buoro** [comment]
Got it @the-mayer . Thank you

**Pull request closed without merging**
